services:
  - type: worker
    name: olasmosfx-smc-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8765599414:AAHZBS8xKvycdL97vfkTD9seFnkDvaKmjug
      - key: CHAT_ID
        value: "6400507534"
